version: "3.81"

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    # environment:
    #   - MONGO_URI=mongodb://myuser:mypassword@mongodb:27017
    env_file:
      - .env

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myuser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongodb_data:/data/lib

volumes:
  mongodb_data:
